#!/usr/bin/env bash

set -eu

outdir="output/blastx/chunk001"
if [[ ! -e "${outdir}" ]]; then
    mkdir -p "${outdir}"
fi

INPUT_CHUNK="output/fasta_chunks/trinity_chunk001.fasta"

blastx -query "${INPUT_CHUNK}" \
    -num_threads 50 \
    -task "blastx-fast" \
    -db "data/blastdb/refseq_protein/refseq_protein" \
    -out "${outdir}/chunk001.xml" \
    -outfmt 5

